# Generated by debtap
# Maintainer: Luke Arms <luke@arms.to>
# Contributor: Jan Kohnert <bughunter@jan-kohnert.de>
# Contributor: Matthew Sexton <wsdmatty@gmail.com>
# Contributor: Lorenz Wellmer
pkgname=clockify-desktop
pkgver=2.6.4
pkgrel=1
pkgdesc="Truly free time tracker for teams, Desktop App"
arch=("x86_64")
url="https://clockify.me"
license=("LicenseRef-custom")
depends=('gtk3' 'libnotify' 'nss' 'libxss' 'libxtst' 'xdg-utils' 'at-spi2-core' 'util-linux-libs' 'libsecret')
source=("$pkgname-$pkgver.deb::https://clockify.me/downloads/Clockify_Setup_x64.deb")
sha512sums=('4497f6117ef21a5ca58603318724d5085d2651cf303d79b6cde339df121a9d75765bba7ab3811a1c99e4405d4cfa39a9046d39bbccaa3a925e8bb3868850e4c0')

package() {
    # Extract package data
    tar xf data.tar.xz -C "${pkgdir}"

    # Install license
    install -Dm644 "${pkgdir}/opt/Clockify/LICENSES.chromium.html" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

    # Fix permission issues
    chmod -R go-w "${pkgdir}/opt/Clockify/resources/assets"

    # Use symbolic links to minimise package size
    ln -srf "${pkgdir}/opt/Clockify/resources/assets/appicons/32x32.png" "${pkgdir}/usr/share/icons/hicolor/32x32/apps/clockify.png"
    ln -srf "${pkgdir}/opt/Clockify/resources/assets/appicons/64x64.png" "${pkgdir}/usr/share/icons/hicolor/64x64/apps/clockify.png"
    ln -srf "${pkgdir}/opt/Clockify/resources/assets/appicons/1024x1024.png" "${pkgdir}/usr/share/icons/hicolor/1024x1024/apps/clockify.png"

    # Remove forgotten temporary build dir
    rm -rf "${pkgdir}/opt/Clockify/resources/app.asar.unpacked/node_modules/active-win/build-tmp-napi-v6"

    # Generate link in PATH
    install -dm755 "${pkgdir}/usr/bin"
    ln -sr "${pkgdir}/opt/Clockify/clockify" "${pkgdir}/usr/bin/clockify"
}
